//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDistrTran.FirstTable {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FirstTable.ITableFstService")]
    public interface ITableFstService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITableFstService/Insert", ReplyAction="http://tempuri.org/ITableFstService/InsertResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/ITableFstService/InsertStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Mandatory)]
        void Insert(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITableFstService/Insert", ReplyAction="http://tempuri.org/ITableFstService/InsertResponse")]
        System.Threading.Tasks.Task InsertAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITableFstService/InsertWithFail", ReplyAction="http://tempuri.org/ITableFstService/InsertWithFailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/ITableFstService/InsertWithFailStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Mandatory)]
        void InsertWithFail(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITableFstService/InsertWithFail", ReplyAction="http://tempuri.org/ITableFstService/InsertWithFailResponse")]
        System.Threading.Tasks.Task InsertWithFailAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITableFstServiceChannel : WCFDistrTran.FirstTable.ITableFstService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TableFstServiceClient : System.ServiceModel.ClientBase<WCFDistrTran.FirstTable.ITableFstService>, WCFDistrTran.FirstTable.ITableFstService {
        
        public TableFstServiceClient() {
        }
        
        public TableFstServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TableFstServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TableFstServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TableFstServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Insert(int value) {
            base.Channel.Insert(value);
        }
        
        public System.Threading.Tasks.Task InsertAsync(int value) {
            return base.Channel.InsertAsync(value);
        }
        
        public void InsertWithFail(int value) {
            base.Channel.InsertWithFail(value);
        }
        
        public System.Threading.Tasks.Task InsertWithFailAsync(int value) {
            return base.Channel.InsertWithFailAsync(value);
        }
    }
}
